"""
=============
Project-wide path and filename constants.

All pipeline stages import from this module so that directory layouts can be
changed in a single place.  Every class is a frozen dataclass — instances are
effectively immutable singletons that carry no logic, only configuration.

Usage
-----
>>> from src.config import ProjectPaths, RawFiles
>>> paths = ProjectPaths()
>>> raw = RawFiles()
>>> df = pd.read_csv(paths.data_raw / raw.train_transaction_csv)
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class ProjectPaths:
    """
    Canonical filesystem paths used across the entire pipeline.

    All paths are expressed relative to the project root so the project is
    portable — clone it anywhere and the paths resolve correctly as long as
    commands are run from the project root directory.

    Attributes
    ----------
    root:
        Project root directory.
    data_raw:
        Raw, unmodified input files (CSV downloads from Kaggle).
        Never overwritten by the pipeline.
    data_interim:
        Intermediate parquet files produced by stages 01–05.
        Safe to delete and regenerate.
    data_processed:
        Final modelling-ready dataset (``dataset_v1.parquet``).
    reports:
        All JSON reports and PNG figures generated by the pipeline.
    """

    root: Path = Path(".")
    data_raw: Path = Path("data/raw")
    data_interim: Path = Path("data/interim")
    data_processed: Path = Path("data/processed")
    reports: Path = Path("reports")


@dataclass(frozen=True)
class RawFiles:
    """
    Filenames of the raw IEEE-CIS Fraud Detection dataset CSVs.

    Place these files under ``data/raw/`` before running the pipeline.
    Download from: https://www.kaggle.com/c/ieee-fraud-detection

    Attributes
    ----------
    train_transaction_csv:
        Transaction-level data (~590K rows, 394 columns).
    train_identity_csv:
        Identity/device data for a subset of transactions (~144K rows, 41 columns).
    """

    train_transaction_csv: str = "train_transaction.csv"
    train_identity_csv: str = "train_identity.csv"


@dataclass(frozen=True)
class InterimFiles:
    """
    Filenames of intermediate parquet files produced by early pipeline stages.

    Attributes
    ----------
    merged_parquet:
        Output of Stage 01 — transaction and identity tables joined on TransactionID.
    """

    merged_parquet: str = "01_merged.parquet"